CREATE VIEW V1 AS
SELECT CUST, MAX(QUANT) MAX_Q, MIN(QUANT) MIN_Q, AVG(QUANT) AVG_Q
FROM SALES
GROUP BY CUST;

CREATE VIEW V2 AS
SELECT V1.CUST, SALES.PROD MAX_PROD, V1.MAX_Q, SALES.MONTH MAX_MONTH, SALES.DAY MAX_DAY, SALES.YEAR MAX_YEAR, SALES.STATE MAX_STATE, V1.MIN_Q, V1.AVG_Q
FROM V1, SALES
WHERE V1.CUST=SALES.CUST AND V1.MAX_Q=SALES.QUANT;

SELECT V2.CUST, V2.MAX_PROD, V2.MAX_Q, V2.MAX_MONTH, V2.MAX_DAY, V2.MAX_YEAR, V2.MAX_STATE, SALES.PROD MIN_PROD, V2.MIN_Q, SALES.MONTH MIN_MONTH, SALES.DAY MIN_DAY, SALES.YEAR MIN_YEAR, SALES.STATE MIN_STATE, V2.AVG_Q
FROM SALES, V2
WHERE V2.CUST=SALES.CUST AND V2.MIN_Q=SALES.QUANT;