DROP TABLE MAX_TABLE;
DROP TABLE MIN_TABLE;
SELECT CUST, MAX(QUANT) AS MAX_Q
INTO MAX_TABLE
FROM SALES
GROUP BY CUST;

SELECT CUST, MIN(QUANT) AS MIN_Q
INTO MIN_TABLE
FROM SALES
GROUP BY CUST;

SELECT SALES.CUST, MAX_TABLE.MAX_Q, SALES.PROD, SALES.MONTH, SALES.DAY, SALES.YEAR, SALES.STATE
INTO MAX_DETAIL
FROM SALES
INNER JOIN MAX_TABLE
ON SALES.CUST=MAX_TABLE.CUST AND SALES.QUANT=MAX_TABLE.MAX_Q;

SELECT SALES.CUST, MIN_TABLE.MIN_Q, SALES.PROD, SALES.MONTH, SALES.DAY, SALES.YEAR, SALES.STATE
INTO MIN_DETAIL
FROM SALES
INNER JOIN MIN_TABLE
ON SALES.CUST=MIN_TABLE.CUST AND SALES.QUANT=MIN_TABLE.MIN_Q;

SELECT MAX_DETAIL.CUST, MAX_DETAIL.MAX_Q, MAX_DETAIL.PROD, MAX_DETAIL.MONTH, MAX_DETAIL.DAY, MAX_DETAIL.YEAR, MAX_DETAIL.STATE,
MIN_DETAIL.MIN_Q, MIN_DETAIL.PROD, MIN_DETAIL.MONTH, MIN_DETAIL.DAY, MIN_DETAIL.YEAR, MIN_DETAIL.STATE
FROM MAX_DETAIL
INNER JOIN MIN_DETAIL
ON MIN_DETAIL.CUST=MAX_DETAIL.CUST;