DROP TABLE STEP_TWO;
DROP TABLE STEP_ONE;
DROP TABLE NAME_TABLE, NY_DETAIL, NJ_DETAIL, CT_DETAIL;
DROP TABLE NY_MAXTABLE;
DROP TABLE NJ_MINTABLE;
DROP TABLE CT_MINTABLE;

SELECT CUST, PROD, MAX(QUANT) AS NY_MAX
INTO NY_MAXTABLE
FROM SALES 
WHERE STATE='NY' AND (YEAR > 1999)
GROUP BY CUST, PROD;
SELECT CUST, PROD, MIN(QUANT) AS NJ_MIN
INTO NJ_MINTABLE
FROM SALES 
WHERE STATE='NJ' AND (YEAR > 1999)
GROUP BY CUST, PROD;
SELECT CUST, PROD, MIN(QUANT) AS CT_MIN
INTO CT_MINTABLE
FROM SALES 
WHERE STATE='CT'
GROUP BY CUST, PROD;
SELECT CUST, PROD
INTO NAME_TABLE
FROM SALES 
GROUP BY CUST, PROD;

SELECT NY_MAXTABLE.CUST, NY_MAXTABLE.PROD, NY_MAXTABLE,NY_MAX, SALES.MONTH, SALES.DAY, SALES.YEAR
INTO NY_DETAIL
FROM NY_MAXTABLE 
INNER JOIN SALES
ON NY_MAXTABLE.NY_MAX=SALES.QUANT AND NY_MAXTABLE.CUST=SALES.CUST AND NY_MAXTABLE.PROD=SALES.PROD;

SELECT NJ_MINTABLE.CUST, NJ_MINTABLE.PROD, NJ_MINTABLE,NJ_MIN, SALES.MONTH, SALES.DAY, SALES.YEAR
INTO NJ_DETAIL
FROM NJ_MINTABLE 
INNER JOIN SALES
ON NJ_MINTABLE.NJ_MIN=SALES.QUANT AND NJ_MINTABLE.CUST=SALES.CUST AND NJ_MINTABLE.PROD=SALES.PROD;

SELECT CT_MINTABLE.CUST, CT_MINTABLE.PROD, CT_MINTABLE,CT_MIN, SALES.MONTH, SALES.DAY, SALES.YEAR
INTO CT_DETAIL
FROM CT_MINTABLE 
INNER JOIN SALES
ON CT_MINTABLE.CT_MIN=SALES.QUANT AND CT_MINTABLE.CUST=SALES.CUST AND CT_MINTABLE.PROD=SALES.PROD;

SELECT NAME_TABLE.CUST, NAME_TABLE.PROD, NY_DETAIL.NY_MAX, NY_DETAIL.MONTH AS NY_MONTH, NY_DETAIL.DAY AS NY_DAY, NY_DETAIL.YEAR AS NY_YEAR
INTO STEP_ONE
FROM NAME_TABLE
LEFT JOIN NY_DETAIL
ON NAME_TABLE.CUST=NY_DETAIL.CUST AND NAME_TABLE.PROD=NY_DETAIL.PROD;


SELECT STEP_ONE.*, NJ_DETAIL.NJ_MIN, NJ_DETAIL.MONTH AS NJ_MONTH, NJ_DETAIL.DAY AS NJ_DAY, NJ_DETAIL.YEAR AS NJ_YEAR
INTO STEP_TWO
FROM STEP_ONE
LEFT JOIN NJ_DETAIL
ON STEP_ONE.CUST=NJ_DETAIL.CUST AND STEP_ONE.PROD=NJ_DETAIL.PROD;

SELECT STEP_TWO.*, CT_DETAIL.CT_MIN, CT_DETAIL.MONTH AS CT_MONTH, CT_DETAIL.DAY AS CT_DAY, CT_DETAIL.YEAR AS CT_YEAR
FROM STEP_TWO
LEFT JOIN CT_DETAIL
ON STEP_TWO.CUST=CT_DETAIL.CUST AND STEP_TWO.PROD=CT_DETAIL.PROD
ORDER BY STEP_TWO.CUST, STEP_TWO.PROD;
