DROP VIEW STEP_TWO;
DROP VIEW STEP_ONE;
DROP VIEW NAME_TABLE, NY_DETAIL, NJ_DETAIL, CT_DETAIL;
DROP VIEW NY_MAXTABLE;
DROP VIEW NJ_MINTABLE;
DROP VIEW CT_MINTABLE;

CREATE VIEW NY_MAXTABLE AS
SELECT CUST, PROD, MAX(QUANT) AS NY_MAX
FROM SALES 
WHERE STATE='NY' AND (YEAR > 1999)
GROUP BY CUST, PROD;

CREATE VIEW NJ_MINTABLE AS
SELECT CUST, PROD, MIN(QUANT) AS NJ_MIN
FROM SALES 
WHERE STATE='NJ' AND (YEAR > 1999)
GROUP BY CUST, PROD;

CREATE VIEW CT_MINTABLE AS
SELECT CUST, PROD, MIN(QUANT) AS CT_MIN
FROM SALES 
WHERE STATE='CT'
GROUP BY CUST, PROD;

CREATE VIEW NAME_TABLE AS
SELECT CUST, PROD
FROM SALES 
GROUP BY CUST, PROD;

CREATE VIEW NY_DETAIL AS
SELECT NY_MAXTABLE.CUST, NY_MAXTABLE.PROD, NY_MAXTABLE,NY_MAX, SALES.MONTH, SALES.DAY, SALES.YEAR
FROM NY_MAXTABLE 
INNER JOIN SALES
ON NY_MAXTABLE.NY_MAX=SALES.QUANT AND NY_MAXTABLE.CUST=SALES.CUST AND NY_MAXTABLE.PROD=SALES.PROD;

CREATE VIEW NJ_DETAIL AS
SELECT NJ_MINTABLE.CUST, NJ_MINTABLE.PROD, NJ_MINTABLE,NJ_MIN, SALES.MONTH, SALES.DAY, SALES.YEAR
FROM NJ_MINTABLE 
INNER JOIN SALES
ON NJ_MINTABLE.NJ_MIN=SALES.QUANT AND NJ_MINTABLE.CUST=SALES.CUST AND NJ_MINTABLE.PROD=SALES.PROD;

CREATE VIEW CT_DETAIL AS
SELECT CT_MINTABLE.CUST, CT_MINTABLE.PROD, CT_MINTABLE,CT_MIN, SALES.MONTH, SALES.DAY, SALES.YEAR
FROM CT_MINTABLE 
INNER JOIN SALES
ON CT_MINTABLE.CT_MIN=SALES.QUANT AND CT_MINTABLE.CUST=SALES.CUST AND CT_MINTABLE.PROD=SALES.PROD;

CREATE VIEW STEP_ONE AS
SELECT NAME_TABLE.CUST, NAME_TABLE.PROD, NY_DETAIL.NY_MAX, NY_DETAIL.MONTH AS NY_MONTH, NY_DETAIL.DAY AS NY_DAY, NY_DETAIL.YEAR AS NY_YEAR
FROM NAME_TABLE
LEFT JOIN NY_DETAIL
ON NAME_TABLE.CUST=NY_DETAIL.CUST AND NAME_TABLE.PROD=NY_DETAIL.PROD;

CREATE VIEW STEP_TWO AS
SELECT STEP_ONE.*, NJ_DETAIL.NJ_MIN, NJ_DETAIL.MONTH AS NJ_MONTH, NJ_DETAIL.DAY AS NJ_DAY, NJ_DETAIL.YEAR AS NJ_YEAR
FROM STEP_ONE
LEFT JOIN NJ_DETAIL
ON STEP_ONE.CUST=NJ_DETAIL.CUST AND STEP_ONE.PROD=NJ_DETAIL.PROD;

SELECT STEP_TWO.*, CT_DETAIL.CT_MIN, CT_DETAIL.MONTH AS CT_MONTH, CT_DETAIL.DAY AS CT_DAY, CT_DETAIL.YEAR AS CT_YEAR
FROM STEP_TWO
LEFT JOIN CT_DETAIL
ON STEP_TWO.CUST=CT_DETAIL.CUST AND STEP_TWO.PROD=CT_DETAIL.PROD


